module.exports = {
    components: {
      categories: [
        {
          name: 'Components',
          include: [
           /* PLOP_INJECT_IMPORT */
           'src/components/Typography/Typography.tsx',
           'src/components/TreeView/TreeView.tsx',
           'src/components/TransferList/TransferList.tsx',
           'src/components/Tooltip/Tooltip.tsx',
           'src/components/ToggleButton/ToggleButton.tsx',
           'src/components/Timeline/Timeline.tsx',
           'src/components/TextField/TextField.tsx',
           'src/components/Tabs/Tabs.tsx',
           'src/components/Table/Table.tsx',
           'src/components/Switch/Switch.tsx',
           'src/components/Stepper/Stepper.tsx',
           'src/components/SpeedDial/SpeedDial.tsx',
           'src/components/Snackbar/Snackbar.tsx',
           'src/components/Slider/Slider.tsx',
           'src/components/Skeleton/Skeleton.tsx',
           'src/components/Select/Select.tsx',
           'src/components/Rating/Rating.tsx',
           'src/components/RadioGroup/RadioGroup.tsx',
           'src/components/Progress/Progress.tsx',
           'src/components/Paper/Paper.tsx',
           'src/components/Pagination/Pagination.tsx',
           'src/components/NavigationRail/NavigationRail.tsx',
           'src/components/Modal/Modal.tsx',
           'src/components/Menu/Menu.tsx',
           'src/components/MaterialIcons/MaterialIcons.tsx',
           'src/components/Masonry/Masonry.tsx',
           'src/components/List/List.tsx',
           'src/components/Link/Link.tsx',
           'src/components/ImageList/ImageList.tsx',
           'src/components/Icons/Icons.tsx',
           'src/components/Drawer/Drawer.tsx',
           'src/components/Divider/Divider.tsx',
           'src/components/Dialog/Dialog.tsx',
           'src/components/DatePickers/DatePickers.tsx',
           'src/components/DataGrid/DataGrid.tsx',
           'src/components/Chip/Chip.tsx',
           'src/components/Checkbox/Checkbox.tsx',
           'src/components/Card/Card.tsx',
           'src/components/ButtonGroup/ButtonGroup.tsx',
           'src/components/FloatingActionButton/FloatingActionButton.tsx',
           'src/components/Button/Button.tsx',
           'src/components/Breadcrumbs/Breadcrumbs.tsx',
           'src/components/BottomNavigation/BottomNavigation.tsx',
           'src/components/Badge/Badge.tsx',
           'src/components/Avatar/Avatar.tsx',
           'src/components/Banner/Banner.tsx',
           'src/components/Autocomplete/Autocomplete.tsx',
           'src/components/AppBarBottom/AppBarBottom.tsx',
           'src/components/AppBarTop/AppBarTop.tsx',
           'src/components/Alert/Alert.tsx',
           'src/components/Accordion/Accordion.tsx',
          
          ],
        },
      ],
      wrapper: 'src/components/UXPinWrapper/UXPinWrapper.tsx',
      webpackConfig: 'webpack.config.js',
    },
    name: 'MUI-UXPin-Merge',
  };
  